### ISSUE TITLE
Tolles Projekt,Bitte um Kontaktaufnahme

### ISSUE THREAD

**Issue by pascalgrotmann** [benjaminwand/3d-printed-labial-pipe#2]
Hallo Benjamin,
Habe leider nichts anderes gefunden dich zu kontaktieren als den Bugtracker zu missbrauchen. Habe als Schüler ein Praktikum als orgelbauer gemacht und würde gerne per email schreiben. pascal.grotmann@gmail.com
Gruß Pascal

**Comment by benjaminwand** [comment]
Ok, hab dir Email geschrieben.
Benjamin
